name: Deploy key to GitHub Pages

on:
  push:
    tags: ["*"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install pandoc
        run: sudo apt-get install -y inkscape pandoc

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate key
        run: |
          mkdir -p dist
          make dist/sdd.md

      - name: Convert to HTML
        run: |
          mkdir -p public
          pandoc -t html dist/sdd.md > public/index.html
          cp -a figures/ public/figures/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./public

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
